name:                    chatops

on:
  issue_comment:
    types:               [created]

jobs:
  chatops:
    runs-on:             ubuntu-latest

    steps:
      - name:            ChatOps
        uses:            peter-evans/slash-command-dispatch@v2
        with:
          token:         ${{ secrets.CHATOPS_PAT }}
          dispatch_type: workflow
          commands:      |
            build
            lint
            test
