name:                  dependencies

on:
  schedule:
  - cron:              "0 0 * * *"
  repository_dispatch:
    types:             [dependencies-command]

jobs:
  dependencies:
    runs-on:           macos-latest

    steps:
    - uses:            actions/checkout@v2
    - uses:            sbertix/spm-dependencies-checker@v1
