name:                  merge

on:
  repository_dispatch:
    types:
      - merge-command

jobs:
  test:
    name:              Merge
    runs-on:           ubuntu-latest

    steps:
    # checkout the current PR of `ComposableRequest`.
    - name:            Checkout
      uses:            actions/checkout@v2
      with:
          token:       ${{ secrets.GITHUB_TOKEN }}
          repository:  ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref:         ${{ github.event.client_payload.pull_request.head.sha }}
    # config author.
    - name:            Config
      id:              config
      run:             |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions"
    # rebase `base` into `head`.
    - name:            Rebase
      run:             |
        git checkout -b test
        git rebase ${{ github.event.client_payload.pull_request.base.sha }}
    # merge `head` into `base`.
    - name:            Merge
      run:             |
        git checkout -b ${{ github.event.client_payload.pull_request.base.ref }} origin/${{ github.event.client_payload.pull_request.base.ref }}
        git merge test -m "chore(merge): merge #${{ github.event.client_payload.pull_request.number }} into \`${{ github.event.client_payload.pull_request.base.ref }}\`" --no-ff
        git push origin ${{ github.event.client_payload.pull_request.base.ref }} --force-with-lease
