name:                              push

on:
  push:
    branches:
      - main
      - bugfixes
      - development
    paths:
      - '**/*.swift'
      - '**/push.yaml'

jobs:
  # lint the code.
  lint:
    name:                          Lint
    runs-on:                       ubuntu-latest

    steps:
      - name:                      Checkout
        uses:                      actions/checkout@v2
      - name:                      Lint
        uses:                      norio-nomura/action-swiftlint@3.1.0
        with:
          args:                    --strict

  # build the library.
  build-combine:
    name:                          Build (Combine)
    needs:                         lint
    runs-on:                       macos-latest

    steps:
    - name:                        Checkout
      uses:                        actions/checkout@v2
    - name:                        Build
      run:                         swift build

  # build the library using `Combine X`.
  build-combine-x:
    name:                          Build (CombineX)
    needs:                         lint
    runs-on:                       macos-latest

    steps:
    - name:                        Checkout
      uses:                        actions/checkout@v2
    - name:                        Build
      env:
        CX_COMBINE_IMPLEMENTATION: combinex
      run:                         swift build
