name:                            release

on:
  push:
    tags:
      - '*'

jobs:
  notify:
    name:                        Create Release
    runs-on:                     ubuntu-latest
    steps:
      - name:                    Checkout code
        uses:                    actions/checkout@v2
      - run:                     git fetch --prune --unshallow --tags
      - name:                    Create changelogs
        id:                      changelogs
        uses:                    heineiuo/create-changelogs@master
      - name:                    Create Release
        id:                      create_release
        uses:                    actions/create-release@latest
        env:
          GITHUB_TOKEN:          ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name:              ${{ github.ref }}
          release_name:          v${{ github.ref }}
          body:                  ${{ steps.changelogs.outputs.changelogs }}
          draft:                 false
          prerelease:            ${{ steps.changelogs.outputs.release_type == 'prerelease' }}
      - name:                    Push to Telegram
        uses:                    appleboy/telegram-action@master
        with:
          to:                    ${{ secrets.TELEGRAM_TO }}
          token:                 ${{ secrets.TELEGRAM_TOKEN }}
          format:                markdown
          args:                  |
            A [new version](${{ steps.create_release.outputs.html_url }}) of **Swiftagram** was just released.
            Please consider updating your code.
  documentation:
    name:                        Create Documentation
    runs-on:                     macos-latest
    needs:                       notify
    steps:
      - uses:                    actions/checkout@v1
      - uses:                    steven0351/publish-jazzy-docs@v1
        with:
          personal_access_token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
          args:                  "--theme fullwidth --author \"Stefano Bertagno\""
