name:                    test

on:
  repository_dispatch:
    types:               [test-command]

jobs:
  test:
    runs-on:             macos-latest

    steps:
    - uses:              actions/checkout@v2
      with:
          token:         ${{ secrets.GITHUB_TOKEN }}
          repository:    ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref:           ${{ github.event.client_payload.pull_request.head.ref }}
    - name:              Test
      env:
        IG_USERNAME:     ${{ secrets.INSTAGRAM_USERNAME }}
        IG_PASSWORD:     ${{ secrets.INSTAGRAM_PASSWORD }}
      run:               swift test --parallel --enable-test-discovery --enable-code-coverage
    - name:              Coverage (1)
      run:               xcrun llvm-cov export -format="lcov" .build/debug/SwiftagramPackageTests.xctest/Contents/MacOS/SwiftagramPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name:              Coverage (2)
      uses:              codecov/codecov-action@v1
      with:
        token:           ${{ secrets.CODECOV_TOKEN }}
      timeout-minutes:   1
      continue-on-error: true
    - name:              Reply (Success)
      uses:              peter-evans/create-or-update-comment@v1
      with:
        comment-id:      ${{ github.event.client_payload.github.payload.comment.id }}
        reaction-type:   hooray
    - name:              Reply (Failure)
      uses:              peter-evans/create-or-update-comment@v1
      if:                ${{ failure() }}
      with:
        issue-number:    ${{ github.event.client_payload.github.payload.issue.number }}
        body:            |
          Hey @${{ github.event.client_payload.github.actor }} :muscle:

          Unfortunately, some of the tests required failed.\
          This might be related to Instagram anti-spam measures (as we're using a single account to test all requests).\
          If that's the case consider testing this commit again in a couple hours.

          Either way, a maintener will get to you soon.
