name:                  test

on:
  workflow_dispatch:
    inputs:
      repo:
        description: ''
        required: true
      head:
        description: ''
        required: true
      base:
        description: ''
        required: true

jobs:
  test:
    name:              Test
    runs-on:           macos-latest

    steps:
    # checkout the current PR of `ComposableRequest`.
    - name:            Checkout
      uses:            actions/checkout@v2
      with:
          token:       ${{ secrets.GITHUB_TOKEN }}
          repository:  ${{ github.event.inputs.repo }}
          ref:         ${{ github.event.inputs.head }}
    # filter updates.
    - uses:            dorny/paths-filter@v2
      id:              changes
      with:
        base:          ${{ github.event.inputs.base }}
        ref:           ${{ github.event.inputs.head }}
        filters:       |
          src:
            - '**/*.swift'
    # run all tests.
    - name:            Test
      if:              steps.changes.outputs.src == 'true'
      run:             swift test --parallel --enable-test-discovery
      env:
        SECRET:        ${{ secrets.SECRET }}
        PASSWORD:      ${{ secrets.PASSWORD }}
